// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';

const bullshitCompanyGoals = [
  'architect front-end models',
  'harness frictionless relationships',
  'strategize user-centric partnerships',
  'synergize virtual systems',
  'facilitate e-business supply-chains',
  'integrate bricks-and-clicks interfaces',
  'morph intuitive e-business',
  'leverage innovative platforms',
  'visualize magnetic web services',
  'orchestrate killer functionalities',
  'scale 24/7 architectures',
  'optimize collaborative experiences',
  'repurpose next-generation initiatives',
  'revolutionize extensible architectures',
  'deploy robust architectures',
  'visualize innovative interfaces',
  'leverage cross-platform infrastructures',
  'seize turn-key content',
  'recontextualize dot-com relationships',
  'iterate wireless metrics',
  'recontextualize dynamic e-tailers',
  'transition visionary methodologies',
  'architect magnetic paradigms',
  'e-enable user-centric e-tailers',
  'brand customized portals',
  'morph end-to-end systems',
  'streamline web-enabled models',
  'evolve ubiquitous initiatives',
  'synergize integrated communities',
  'engineer transparent paradigms',
  'engineer dynamic e-commerce',
  'matrix one-to-one content',
  'disintermediate visionary mindshare',
  'matrix 24/365 eyeballs',
  'whiteboard rich technologies',
  'exploit virtual e-commerce',
  'extend innovative architectures',
  'scale collaborative models',
  'envisioneer killer users',
  'harness viral deliverables',
  'synergize virtual action-items',
  'generate plug-and-play schemas',
  'streamline sticky e-commerce',
  'orchestrate proactive e-markets',
  'redefine granular web-readiness',
  'streamline leading-edge metrics',
  'implement transparent solutions',
  'iterate turn-key e-markets',
  'maximize visionary metrics',
  'seize revolutionary networks',
  'empower end-to-end synergies',
  'reintermediate turn-key supply-chains',
  'generate dynamic systems',
  'synthesize dot-com architectures',
  'e-enable distributed vortals',
  'generate back-end niches',
  'mesh value-added web-readiness',
  'empower holistic supply-chains',
  'integrate turn-key channels',
  'revolutionize plug-and-play relationships',
  'visualize open-source action-items',
  'revolutionize cross-media portals',
  'engineer 24/7 bandwidth',
  'transform global vortals',
  'exploit efficient initiatives',
  'monetize collaborative markets',
  'drive interactive mindshare',
  'exploit clicks-and-mortar functionalities',
  'integrate clicks-and-mortar ROI',
  'generate out-of-the-box applications',
  'synthesize back-end web-readiness',
  'whiteboard web-enabled eyeballs',
  'visualize virtual metrics',
  'engage e-business e-commerce',
  'unleash next-generation platforms',
  'morph impactful experiences',
  'generate cutting-edge synergies',
  'grow e-business platforms',
  'extend cross-media systems',
  'reinvent interactive vortals',
  'benchmark virtual schemas',
  'optimize intuitive applications',
  'exploit 24/7 e-services',
  'enable innovative supply-chains',
  'incentivize proactive initiatives',
  'maximize value-added convergence',
  'leverage collaborative ROI',
  'envisioneer robust synergies',
  'aggregate turn-key applications',
  'enable B2B partnerships',
  'orchestrate virtual ROI',
  'strategize wireless vortals',
  'strategize dynamic content',
  'drive dynamic metrics',
  'whiteboard transparent infomediaries',
  'target holistic metrics',
  'grow robust supply-chains',
  'deploy integrated platforms',
  'utilize granular methodologies',
  'exploit cross-platform infomediaries',
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<{
    results: string[];
    total: number;
  }>
) {
  const query = req.query as { offset?: string; limit?: string };
  const offset = query.offset ? parseInt(query.offset) : 0;
  const limit = query.limit ? parseInt(query.limit) : 10;
  const results = bullshitCompanyGoals.slice(offset, offset + limit);
  res.status(200).json({
    results,
    total: bullshitCompanyGoals.length,
  });
}
